# pyproject.toml
[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geoshapes"
version = "0.3.0"
dependencies = [
    "click>=8.1.3",
    "pytest>=7.4.0",
]
